### ISSUE TITLE
Color coding of risk tree is unclear

### ISSUE THREAD

**Issue by stephenjust** [SAP/risk-explorer-for-software-supply-chains#32]
This took is extremely interesting, but I'm trying to understand the color coding:
![image](https://user-images.githubusercontent.com/3144757/182500840-95919d39-b68e-4f00-b9a5-0b70a105d5de.png)

I don't see these colors documented anywhere or a legend of any sort. Is there something that could be done to make this easier to interpret?

**Comment by piergiorgioladisa** [comment]
Hi @stephenjust,

thank you very much for the appreciation and for creating the issue. I will work on that and add a legend to make clearer the meaning of the colors.
In the meanwhile I can recommend to you to read the paper associated to the Risk Explorer tool, which is available for the moment on [Arxiv](https://arxiv.org/abs/2204.04008) and which also have a legend for the colors.

In summary, we used same colors for those group of attack vectors that appears multiple time in the tree because they can be performed in different context.
In particular:

- Red is used for attack vectors related to the compromise of a user
- Green is used for attack vectors related to the compromise of a system
- Yellow is used for attack vectors related to social-engineering attack on project maintainer
- The dashed stroke for the blue node is a recursion to the root node. In fact, this is the case of the attack vector "Infect through Malicious Component", which requires basically to perform a supply chain attack
