### ISSUE TITLE
Review classification of protestware

### ISSUE THREAD

**Issue by henrikplate** [SAP/risk-explorer-for-software-supply-chains#46]
@piergiorgioladisa and @serenaponta We already discussed several times how to classify the peacenotwar protestware. Right now, it is assigned to the node `Develop malicious package from scratch`, which in its current definition assumes that the attacker planned from the very beginning to misuse the package at some point in time for delivering malware. It somehow does not cover the case of a benign attacker turning malicious (for whatever reasons).

Looking at the attack tree, there are at least three ways to better reflect protestware:
- Update existing attack vector `Develop malicious package from scratch`,
- Update existing vector `Bribe or blackmail legitimate user` to something like `Legit user is politicized, blackmailed or bribed` (but that somehow mixes internal and external motivations), or
- Create new attack vector `Contribute as maintainer > Change ethos`, which can be formulated in such a way that it covers both intrinsic and extrinsic motivations for somebody to change his attitude or ethos and misuse an existing legitimate package as malware (for expressing political opinions or other reasons).

What do you think?

**Comment by piergiorgioladisa** [comment]
@henrikplate among the three proposals, I would be more in favor of the third one. In particular:

- I would leave the meaning of the AV `Develop malicious package from scratch` as it is, and I would not mix meanings since this would create more confusion than clarity IMHO
- For the same reason as above, I would not put multiple AVs into one. So this why I prefer to rather add a sibling to `Bribe or blackmail legitimate user` so that it will be repeated below all the parents `Inject Into Sources of Legitimate Package`, `..Build` etc.. and that would represent all viable options for a disgruntled maintainer

**Comment by henrikplate** [comment]
@serenaponta also prefers the 3rd option. Since we all agree, I will add this new attack vector later today.
